2024-04-13 13:15:05,444 INFO    MainThread:372714 [wandb_setup.py:_flush():76] Current SDK version is 0.16.6
2024-04-13 13:15:05,444 INFO    MainThread:372714 [wandb_setup.py:_flush():76] Configure stats pid to 372714
2024-04-13 13:15:05,444 INFO    MainThread:372714 [wandb_setup.py:_flush():76] Loading settings from /home/jeongseokoh/.config/wandb/settings
2024-04-13 13:15:05,445 INFO    MainThread:372714 [wandb_setup.py:_flush():76] Loading settings from /data2/jeongseokoh/jeongseokoh/bnn/wandb/settings
2024-04-13 13:15:05,445 INFO    MainThread:372714 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-04-13 13:15:05,445 INFO    MainThread:372714 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-04-13 13:15:05,445 INFO    MainThread:372714 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-04-13 13:15:05,445 INFO    MainThread:372714 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-04-13 13:15:05,445 INFO    MainThread:372714 [wandb_init.py:_log_setup():521] Logging user logs to /data2/jeongseokoh/jeongseokoh/bnn/wandb/run-20240413_131505-etstd70n/logs/debug.log
2024-04-13 13:15:05,445 INFO    MainThread:372714 [wandb_init.py:_log_setup():522] Logging internal logs to /data2/jeongseokoh/jeongseokoh/bnn/wandb/run-20240413_131505-etstd70n/logs/debug-internal.log
2024-04-13 13:15:05,446 INFO    MainThread:372714 [wandb_init.py:init():561] calling init triggers
2024-04-13 13:15:05,446 INFO    MainThread:372714 [wandb_init.py:init():568] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.01, 'architecture': 'Scratch', 'dataset': 'de,en', 'epochs': 10}
2024-04-13 13:15:05,446 INFO    MainThread:372714 [wandb_init.py:init():586] re-initializing run, found existing run on stack: 36ccy81b
2024-04-13 13:15:05,448 INFO    MainThread:372714 [wandb_run.py:_finish():2064] finishing run luke0112/Sparse_plane/36ccy81b
2024-04-13 13:15:05,449 INFO    MainThread:372714 [jupyter.py:save_history():445] not saving jupyter history
2024-04-13 13:15:05,449 INFO    MainThread:372714 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-04-13 13:15:05,449 INFO    MainThread:372714 [wandb_init.py:_jupyter_teardown():449] cleaning up jupyter logic
2024-04-13 13:15:05,449 INFO    MainThread:372714 [wandb_run.py:_atexit_cleanup():2304] got exitcode: 0
2024-04-13 13:15:05,449 INFO    MainThread:372714 [wandb_run.py:_restore():2287] restore
2024-04-13 13:15:05,450 INFO    MainThread:372714 [wandb_run.py:_restore():2293] restore done
2024-04-13 13:15:08,633 INFO    MainThread:372714 [wandb_init.py:init():611] starting backend
2024-04-13 13:15:08,633 INFO    MainThread:372714 [wandb_init.py:init():615] setting up manager
2024-04-13 13:15:08,635 INFO    MainThread:372714 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-04-13 13:15:08,636 INFO    MainThread:372714 [wandb_init.py:init():623] backend started and connected
2024-04-13 13:15:08,643 INFO    MainThread:372714 [wandb_run.py:_label_probe_notebook():1299] probe notebook
2024-04-13 13:15:08,644 INFO    MainThread:372714 [wandb_run.py:_label_probe_notebook():1309] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-04-13 13:15:08,644 INFO    MainThread:372714 [wandb_init.py:init():715] updated telemetry
2024-04-13 13:15:08,660 INFO    MainThread:372714 [wandb_init.py:init():748] communicating run to backend with 90.0 second timeout
