2024-04-12 11:29:57,129 INFO    MainThread:284119 [wandb_setup.py:_flush():76] Current SDK version is 0.16.6
2024-04-12 11:29:57,130 INFO    MainThread:284119 [wandb_setup.py:_flush():76] Configure stats pid to 284119
2024-04-12 11:29:57,130 INFO    MainThread:284119 [wandb_setup.py:_flush():76] Loading settings from /home/jeongseokoh/.config/wandb/settings
2024-04-12 11:29:57,130 INFO    MainThread:284119 [wandb_setup.py:_flush():76] Loading settings from /data2/jeongseokoh/jeongseokoh/bnn/wandb/settings
2024-04-12 11:29:57,130 INFO    MainThread:284119 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-04-12 11:29:57,130 INFO    MainThread:284119 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-04-12 11:29:57,130 INFO    MainThread:284119 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-04-12 11:29:57,130 INFO    MainThread:284119 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-04-12 11:29:57,131 INFO    MainThread:284119 [wandb_init.py:_log_setup():521] Logging user logs to /data2/jeongseokoh/jeongseokoh/bnn/wandb/run-20240412_112957-zdlc89y5/logs/debug.log
2024-04-12 11:29:57,131 INFO    MainThread:284119 [wandb_init.py:_log_setup():522] Logging internal logs to /data2/jeongseokoh/jeongseokoh/bnn/wandb/run-20240412_112957-zdlc89y5/logs/debug-internal.log
2024-04-12 11:29:57,131 INFO    MainThread:284119 [wandb_init.py:_jupyter_setup():467] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7fda0ca98200>
2024-04-12 11:29:57,131 INFO    MainThread:284119 [wandb_init.py:init():561] calling init triggers
2024-04-12 11:29:57,131 INFO    MainThread:284119 [wandb_init.py:init():568] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.01, 'architecture': 'Scratch', 'dataset': 'de,en', 'epochs': 10}
2024-04-12 11:29:57,131 INFO    MainThread:284119 [wandb_init.py:init():611] starting backend
2024-04-12 11:29:57,131 INFO    MainThread:284119 [wandb_init.py:init():615] setting up manager
2024-04-12 11:29:57,132 INFO    MainThread:284119 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-04-12 11:29:57,135 INFO    MainThread:284119 [wandb_init.py:init():623] backend started and connected
2024-04-12 11:29:57,141 INFO    MainThread:284119 [wandb_run.py:_label_probe_notebook():1299] probe notebook
2024-04-12 11:29:57,141 INFO    MainThread:284119 [wandb_run.py:_label_probe_notebook():1309] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-04-12 11:29:57,141 INFO    MainThread:284119 [wandb_init.py:init():715] updated telemetry
2024-04-12 11:29:57,154 INFO    MainThread:284119 [wandb_init.py:init():748] communicating run to backend with 90.0 second timeout
2024-04-12 11:29:57,597 INFO    MainThread:284119 [wandb_run.py:_on_init():2357] communicating current version
2024-04-12 11:29:57,694 INFO    MainThread:284119 [wandb_run.py:_on_init():2366] got version response 
2024-04-12 11:29:57,694 INFO    MainThread:284119 [wandb_init.py:init():799] starting run threads in backend
2024-04-12 11:29:58,910 WARNING MainThread:284119 [wandb_init.py:init():1203] interrupted
Traceback (most recent call last):
  File "/data2/jeongseokoh/miniconda3/envs/env01/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1181, in init
    run = wi.init()
          ^^^^^^^^^
  File "/data2/jeongseokoh/miniconda3/envs/env01/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 812, in init
    run_start_result = run_start_handle.wait(timeout=30)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data2/jeongseokoh/miniconda3/envs/env01/lib/python3.12/site-packages/wandb/sdk/lib/mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data2/jeongseokoh/miniconda3/envs/env01/lib/python3.12/site-packages/wandb/sdk/lib/mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data2/jeongseokoh/miniconda3/envs/env01/lib/python3.12/site-packages/wandb/sdk/lib/mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data2/jeongseokoh/miniconda3/envs/env01/lib/python3.12/threading.py", line 655, in wait
    signaled = self._cond.wait(timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data2/jeongseokoh/miniconda3/envs/env01/lib/python3.12/threading.py", line 359, in wait
    gotit = waiter.acquire(True, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
2024-04-12 11:30:05,914 INFO    MainThread:284119 [wandb_settings.py:_apply_login():1943] Applying login settings: {}
2024-04-12 11:30:05,928 INFO    MainThread:284119 [wandb_setup.py:_flush():76] Current SDK version is 0.16.6
2024-04-12 11:30:05,928 INFO    MainThread:284119 [wandb_setup.py:_flush():76] Configure stats pid to 284119
2024-04-12 11:30:05,928 INFO    MainThread:284119 [wandb_setup.py:_flush():76] Loading settings from /home/jeongseokoh/.config/wandb/settings
2024-04-12 11:30:05,928 INFO    MainThread:284119 [wandb_setup.py:_flush():76] Loading settings from /data2/jeongseokoh/jeongseokoh/bnn/wandb/settings
2024-04-12 11:30:05,929 INFO    MainThread:284119 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-04-12 11:30:05,929 INFO    MainThread:284119 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-04-12 11:30:05,929 INFO    MainThread:284119 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-04-12 11:30:05,929 INFO    MainThread:284119 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-04-12 11:30:05,929 INFO    MainThread:284119 [wandb_init.py:_log_setup():521] Logging user logs to /data2/jeongseokoh/jeongseokoh/bnn/wandb/run-20240412_113005-qwkvkhq0/logs/debug.log
2024-04-12 11:30:05,929 INFO    MainThread:284119 [wandb_init.py:_log_setup():522] Logging internal logs to /data2/jeongseokoh/jeongseokoh/bnn/wandb/run-20240412_113005-qwkvkhq0/logs/debug-internal.log
2024-04-12 11:30:05,930 INFO    MainThread:284119 [wandb_init.py:init():561] calling init triggers
2024-04-12 11:30:05,930 INFO    MainThread:284119 [wandb_init.py:init():568] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.01, 'architecture': 'Scratch', 'dataset': 'de,en', 'epochs': 10}
2024-04-12 11:30:05,930 INFO    MainThread:284119 [wandb_init.py:init():611] starting backend
2024-04-12 11:30:05,930 INFO    MainThread:284119 [wandb_init.py:init():615] setting up manager
2024-04-12 11:30:05,931 INFO    MainThread:284119 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-04-12 11:30:05,932 INFO    MainThread:284119 [wandb_init.py:init():623] backend started and connected
2024-04-12 11:30:05,937 INFO    MainThread:284119 [wandb_run.py:_label_probe_notebook():1299] probe notebook
2024-04-12 11:30:05,937 INFO    MainThread:284119 [wandb_run.py:_label_probe_notebook():1309] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-04-12 11:30:05,938 INFO    MainThread:284119 [wandb_init.py:init():715] updated telemetry
2024-04-12 11:30:05,948 INFO    MainThread:284119 [wandb_init.py:init():748] communicating run to backend with 90.0 second timeout
2024-04-12 11:30:06,370 INFO    MainThread:284119 [wandb_run.py:_on_init():2357] communicating current version
2024-04-12 11:30:06,438 INFO    MainThread:284119 [wandb_run.py:_on_init():2366] got version response 
2024-04-12 11:30:06,438 INFO    MainThread:284119 [wandb_init.py:init():799] starting run threads in backend
2024-04-12 11:30:10,362 INFO    MainThread:284119 [wandb_run.py:_console_start():2335] atexit reg
2024-04-12 11:30:10,363 INFO    MainThread:284119 [wandb_run.py:_redirect():2190] redirect: wrap_raw
2024-04-12 11:30:10,363 INFO    MainThread:284119 [wandb_run.py:_redirect():2255] Wrapping output streams.
2024-04-12 11:30:10,363 INFO    MainThread:284119 [wandb_run.py:_redirect():2280] Redirects installed.
2024-04-12 11:30:10,363 INFO    MainThread:284119 [wandb_init.py:init():842] run started, returning control to user process
2024-04-12 11:30:50,888 INFO    MainThread:284119 [wandb_setup.py:_flush():76] Current SDK version is 0.16.6
2024-04-12 11:30:50,889 INFO    MainThread:284119 [wandb_setup.py:_flush():76] Configure stats pid to 284119
2024-04-12 11:30:50,889 INFO    MainThread:284119 [wandb_setup.py:_flush():76] Loading settings from /home/jeongseokoh/.config/wandb/settings
2024-04-12 11:30:50,889 INFO    MainThread:284119 [wandb_setup.py:_flush():76] Loading settings from /data2/jeongseokoh/jeongseokoh/bnn/wandb/settings
2024-04-12 11:30:50,889 INFO    MainThread:284119 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-04-12 11:30:50,889 INFO    MainThread:284119 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-04-12 11:30:50,890 INFO    MainThread:284119 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-04-12 11:30:50,890 INFO    MainThread:284119 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-04-12 11:30:50,890 INFO    MainThread:284119 [wandb_init.py:_log_setup():521] Logging user logs to /data2/jeongseokoh/jeongseokoh/bnn/wandb/run-20240412_113050-gohkp9la/logs/debug.log
2024-04-12 11:30:50,891 INFO    MainThread:284119 [wandb_init.py:_log_setup():522] Logging internal logs to /data2/jeongseokoh/jeongseokoh/bnn/wandb/run-20240412_113050-gohkp9la/logs/debug-internal.log
2024-04-12 11:30:50,891 INFO    MainThread:284119 [wandb_init.py:init():561] calling init triggers
2024-04-12 11:30:50,891 INFO    MainThread:284119 [wandb_init.py:init():568] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.01, 'architecture': 'Scratch', 'dataset': 'de,en', 'epochs': 10}
2024-04-12 11:30:50,891 INFO    MainThread:284119 [wandb_init.py:init():586] re-initializing run, found existing run on stack: qwkvkhq0
2024-04-12 11:30:50,894 INFO    MainThread:284119 [wandb_run.py:_finish():2064] finishing run luke0112/Sparse_plane/qwkvkhq0
2024-04-12 11:30:50,894 INFO    MainThread:284119 [wandb_run.py:_atexit_cleanup():2304] got exitcode: 0
2024-04-12 11:30:50,894 INFO    MainThread:284119 [wandb_run.py:_restore():2287] restore
2024-04-12 11:30:50,895 INFO    MainThread:284119 [wandb_run.py:_restore():2293] restore done
2024-04-12 11:30:53,901 WARNING MsgRouterThr:284119 [router.py:message_loop():77] message_loop has been closed
2024-04-12 11:36:18,923 INFO    MainThread:284119 [wandb_init.py:init():611] starting backend
2024-04-12 11:36:18,924 INFO    MainThread:284119 [wandb_init.py:init():615] setting up manager
2024-04-12 11:36:18,926 INFO    MainThread:284119 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-04-12 11:36:18,927 INFO    MainThread:284119 [wandb_init.py:init():623] backend started and connected
2024-04-12 11:36:18,933 INFO    MainThread:284119 [wandb_run.py:_label_probe_notebook():1299] probe notebook
2024-04-12 11:36:18,933 INFO    MainThread:284119 [wandb_run.py:_label_probe_notebook():1309] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-04-12 11:36:18,933 INFO    MainThread:284119 [wandb_init.py:init():715] updated telemetry
2024-04-12 11:36:18,947 INFO    MainThread:284119 [wandb_init.py:init():748] communicating run to backend with 90.0 second timeout
